# Generated by Django 3.0.8 on 2022-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Creado el')),
                ('name', models.CharField(default='DESCONOCIDO', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('activa', 'activa'), ('inactiva', 'inactiva')], max_length=100, null=True)),
            ],
        ),
    ]
