# Generated by Django 3.0.8 on 2022-03-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Creado el')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status_transaction', models.CharField(blank=True, choices=[('closed', 'closed'), ('reversed', 'reversed'), ('pending', 'pending')], max_length=100, null=True)),
                ('status_approved', models.BooleanField(blank=True, null=True)),
                ('final_payment', models.BooleanField(blank=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
    ]
