CREATE ROLE plerkuser WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:NuuGg45ij3w2QAmSHgdW/Q==$l2Gh1i7tay5KUtGqdxPojiFhTegIukOHaOMocAIq7/c=:RXW1SMKhaLVHwWVUFs2+vZFVMNXXbK7CUPYUtjfr1xU=';

CREATE DATABASE plerk
WITH
OWNER = plerkuser
ENCODING = 'UTF8'
LC_COLLATE = 'C'
LC_CTYPE = 'C'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;